--Phan quyen--

--Tao login
EXEC SP_ADDLOGIN 'Login_1', 'AAAA@123'
EXEC SP_ADDLOGIN 'Login_2', 'BBBB@123'
EXEC SP_ADDLOGIN 'Login_3', 'CCCC@123'
EXEC SP_ADDLOGIN 'Login_4', 'DDDD@123'

--Tao user
Create User user_1 From Login Login_1 with default_schema = QLPHONGKHAM
Create User user_2 FROM Login Login_2 with default_schema = QLPHONGKHAM
Create User user_3 FROM Login Login_3 with default_schema = QLPHONGKHAM
Create User user_4 FROM Login Login_4 with default_schema = QLPHONGKHAM

--Tao role
EXEC SP_ADDROLE 'KHACH'
EXEC SP_ADDROLE 'BENHNHAN'
EXEC SP_ADDROLE 'NHASI'
EXEC SP_ADDROLE 'QUANTRI'
EXEC SP_ADDROLE 'NHANVIEN'

--Add rolve
exec sp_addrolemember 'BENHNHAN','user_1'
exec sp_addrolemember 'NHASI','user_2'
exec sp_addrolemember 'QUANTRI','user_3'
exec sp_addrolemember 'NHANVIEN','user_4'

--Gan quyen
--BENH NHAN CHUA CO TAI KHOAN
GRANT select 
ON NHASI(MANS, HOTEN)
TO KHACH

GRANT select 
ON THUOC(MATHUOC, TENTHUOC, DONVI, DONGIA)
TO KHACH

GRANT select 
ON DICHVU(MADV, TENDV, DONGIA)
TO KHACH

GRANT SELECT 
ON LICHLAMVIEC 
TO KHACH

GRANT SELECT, INSERT, DELETE
ON LICHKHAM 
TO KHACH 

--BENH NHAN DA CO TAI KHOAN
GRANT select, UPDATE(MATKHAU, HOTEN, NGAYSINH, DIACHI) 
ON BENHNHAN
TO BENHNHAN

GRANT select 
ON NHASI(MANS, HOTEN)
TO BENHNHAN

GRANT select 
ON THUOC(MATHUOC, TENTHUOC, DONVI, DONGIA)
TO BENHNHAN

GRANT select 
ON DICHVU(MADV, TENDV, DONGIA)
TO BENHNHAN

GRANT SELECT 
ON LICHLAMVIEC 
TO BENHNHAN

GRANT SELECT, INSERT, DELETE
ON LICHKHAM 
TO BENHNHAN 

GRANT SELECT 
ON HOADON
TO BENHNHAN

GRANT SELECT 
ON TOATHUOC
TO BENHNHAN

GRANT SELECT 
ON DICHVUCHIDINH
TO BENHNHAN

--NHA SI
GRANT INSERT, SELECT(MABN, HOTEN, NGAYSINH)
ON BENHNHAN
TO NHASI 

GRANT SELECT, INSERT, UPDATE
ON HOADON
TO NHASI

GRANT SELECT, INSERT, UPDATE
ON TOATHUOC
TO NHASI

GRANT SELECT, INSERT, UPDATE
ON DICHVUCHIDINH
TO NHASI

GRANT UPDATE, SELECT, INSERT
ON LICHLAMVIEC
TO NHASI

GRANT SELECT 
ON THUOC
TO NHASI

GRANT SELECT
ON DICHVU
TO NHASI

--NHAN VIEN
GRANT SELECT, INSERT, DELETE 
ON LICHKHAM
TO NHANVIEN

GRANT SELECT 
ON TOATHUOC
TO NHANVIEN

GRANT SELECT 
ON DICHVUCHIDINH
TO NHANVIEN

GRANT SELECT
ON HOADON
TO NHANVIEN

--QUAN TRI
GRANT SELECT, INSERT, DELETE, UPDATE 
ON THUOC
TO QUANTRI

GRANT SELECT, INSERT, DELETE, UPDATE 
ON DICHVU
TO QUANTRI

GRANT SELECT, INSERT, DELETE, UPDATE 
ON NHANVIEN
TO QUANTRI

GRANT SELECT, INSERT, DELETE, UPDATE 
ON BENHNHAN
TO QUANTRI

GRANT SELECT, INSERT, DELETE, UPDATE 
ON NHASI
TO QUANTRI