--Phan quyen
--Tao login
GO
EXEC SP_ADDLOGIN 'benhnhan', 'benhnhan'
EXEC SP_ADDLOGIN 'nhasi', 'nhasi'
EXEC SP_ADDLOGIN 'quantri', 'quantri'
EXEC SP_ADDLOGIN 'nhanvien', 'nhanvien'
EXEC SP_ADDLOGIN 'khach', 'khach'

--Tao user
Create User user_1 From Login benhnhan with default_schema = QLPHONGKHAM
Create User user_2 FROM Login nhasi with default_schema = QLPHONGKHAM
Create User user_3 FROM Login quantri with default_schema = QLPHONGKHAM
Create User user_4 FROM Login nhanvien with default_schema = QLPHONGKHAM
Create User user_5 FROM Login khach with default_schema = QLPHONGKHAM

--Tao role
EXEC SP_ADDROLE 'KHACH'
EXEC SP_ADDROLE 'BENHNHAN'
EXEC SP_ADDROLE 'NHASI'
EXEC SP_ADDROLE 'QUANTRI'
EXEC SP_ADDROLE 'NHANVIEN'

--Add role
exec sp_addrolemember 'BENHNHAN','user_1'
exec sp_addrolemember 'NHASI','user_2'
exec sp_addrolemember 'QUANTRI','user_3'
exec sp_addrolemember 'NHANVIEN','user_4'
exec sp_addrolemember 'KHACH','user_5'

GO
--BENH NHAN CHUA CO TAI KHOAN
GRANT select 
ON NHASI(MANS, HOTEN)
TO KHACH

GRANT select 
ON THUOC(MATHUOC, TENTHUOC, DONVI, DONGIA)
TO KHACH

GRANT select 
ON DICHVU(MADV, TENDV, DONGIA)
TO KHACH

GRANT SELECT 
ON LICHLAMVIEC 
TO KHACH

GRANT SELECT, INSERT, DELETE
ON LICHKHAM 
TO KHACH 

--BENH NHAN DA CO TAI KHOAN
GRANT select, UPDATE(MATKHAU, HOTEN, NGAYSINH, DIACHI) 
ON BENHNHAN
TO BENHNHAN

GRANT select 
ON NHASI(MANS, HOTEN)
TO BENHNHAN

GRANT select 
ON THUOC(MATHUOC, TENTHUOC, DONVI, DONGIA)
TO BENHNHAN

GRANT select 
ON DICHVU(MADV, TENDV, DONGIA)
TO BENHNHAN

GRANT SELECT 
ON LICHLAMVIEC 
TO BENHNHAN

GRANT SELECT, INSERT, DELETE
ON LICHKHAM 
TO BENHNHAN 

GRANT SELECT 
ON CHITIETPHIENKHAM
TO BENHNHAN

GRANT SELECT 
ON TOATHUOC
TO BENHNHAN

GRANT SELECT 
ON DICHVUCHIDINH
TO BENHNHAN

--NHA SI
GRANT INSERT, SELECT(MABN, HOTEN, NGAYSINH)
ON BENHNHAN
TO NHASI 

GRANT SELECT, INSERT, UPDATE
ON CHITIETPHIENKHAM
TO NHASI

GRANT SELECT, INSERT, UPDATE
ON TOATHUOC
TO NHASI

GRANT SELECT, INSERT, UPDATE
ON DICHVUCHIDINH
TO NHASI

GRANT UPDATE, SELECT, INSERT
ON LICHLAMVIEC
TO NHASI

GRANT SELECT 
ON THUOC
TO NHASI

GRANT SELECT
ON DICHVU
TO NHASI

--NHAN VIEN
GRANT SELECT, INSERT, DELETE 
ON LICHKHAM
TO NHANVIEN

GRANT SELECT 
ON TOATHUOC
TO NHANVIEN

GRANT SELECT 
ON DICHVUCHIDINH
TO NHANVIEN

GRANT SELECT
ON CHITIETPHIENKHAM
TO NHANVIEN

--QUAN TRI
GRANT SELECT, INSERT, DELETE, UPDATE 
ON THUOC
TO QUANTRI

GRANT SELECT, INSERT, DELETE, UPDATE 
ON DICHVU
TO QUANTRI

GRANT SELECT, INSERT, DELETE, UPDATE 
ON NHANVIEN
TO QUANTRI

GRANT SELECT, INSERT, DELETE, UPDATE 
ON BENHNHAN
TO QUANTRI

GRANT SELECT, INSERT, DELETE, UPDATE 
ON NHASI
TO QUANTRI

--PHAN QUYEN EXEC
GO
GRANT EXEC ON GET_INFO_NHANVIEN TO KHACH 
GRANT EXEC ON GET_INFO_NHANVIEN_BY_ID TO KHACH  
GRANT EXEC ON GET_INFO_NHANVIEN_BY_NAME TO KHACH 
GRANT EXEC ON GET_INFO_NHANVIEN_BY_PHONENUMBER TO KHACH
GRANT EXEC ON GET_INFO_NHASI TO KHACH 
GRANT EXEC ON GET_INFO_NHASI_BY_ID TO KHACH
GRANT EXEC ON GET_INFO_NHASI_BY_NAME TO KHACH 
GRANT EXEC ON GET_INFO_NHASI_BY_PHONENUMBER TO KHACH
GRANT EXEC ON GET_INFO_THUOC TO KHACH  
GRANT EXEC ON GET_INFO_THUOC_BY_ID TO KHACH  
GRANT EXEC ON GET_INFO_THUOC_BY_NAME TO KHACH  
GRANT EXEC ON GET_INFO_DICHVU TO KHACH  
GRANT EXEC ON GET_INFO_DICHVU_BY_NAME TO KHACH  
GRANT EXEC ON GET_LICHKHAM_DETAIL TO KHACH  
GRANT EXEC ON GET_LICHKHAM_DETAIL_FOR_BENHNHAN TO KHACH 
GRANT EXEC ON GET_LICHKHAM_DETAIL_OF_NHASI TO KHACH  
GRANT EXEC ON GET_LICHLAMVIEC_DETAIL TO KHACH  
GRANT EXEC ON GET_LICHKHAM_DETAIL_OF_NHASI TO KHACH  
GRANT EXEC ON GET_LICHLAMVIEC_DETAIL_OF_NHASI TO KHACH  
GRANT EXEC ON GET_LICHLAMVIEC_DETAIL_FREE TO KHACH  
GRANT EXEC ON GET_LICHLAMVIEC_DETAIL_FREE_OF_NHASI TO KHACH  
GRANT EXEC ON GET_DICHVUCHIDINH_DETAIL TO KHACH  
GRANT EXEC ON GET_TOATHUOC_DETAIL TO KHACH  
GRANT EXEC ON INSERT_INTO_BENHNHAN TO KHACH 
GRANT EXEC ON REGISTER_LICHKHAM TO KHACH  
GRANT EXEC ON DROP_LICHKHAM TO KHACH  
GRANT EXEC ON CHANGE_LICHKHAM TO KHACH  
GRANT EXEC ON SIGIN TO KHACH


GRANT EXEC ON GET_INFO_NHANVIEN TO BENHNHAN 
GRANT EXEC ON GET_INFO_NHANVIEN_BY_ID TO BENHNHAN  
GRANT EXEC ON GET_INFO_NHANVIEN_BY_NAME TO BENHNHAN 
GRANT EXEC ON GET_INFO_NHANVIEN_BY_PHONENUMBER TO BENHNHAN
GRANT EXEC ON GET_INFO_NHASI TO BENHNHAN 
GRANT EXEC ON GET_INFO_NHASI_BY_ID TO BENHNHAN
GRANT EXEC ON GET_INFO_NHASI_BY_NAME TO BENHNHAN 
GRANT EXEC ON GET_INFO_NHASI_BY_PHONENUMBER TO BENHNHAN
GRANT EXEC ON GET_INFO_BENHNHAN_BY_ID TO BENHNHAN  
GRANT EXEC ON GET_INFO_THUOC TO BENHNHAN  
GRANT EXEC ON GET_INFO_THUOC_BY_ID TO BENHNHAN  
GRANT EXEC ON GET_INFO_THUOC_BY_NAME TO BENHNHAN  
GRANT EXEC ON GET_INFO_DICHVU TO BENHNHAN  
GRANT EXEC ON GET_INFO_DICHVU_BY_NAME TO BENHNHAN  
GRANT EXEC ON GET_LICHKHAM_DETAIL TO BENHNHAN  
GRANT EXEC ON GET_LICHKHAM_DETAIL_OF_NHASI TO BENHNHAN  
GRANT EXEC ON GET_LICHLAMVIEC_DETAIL TO BENHNHAN  
GRANT EXEC ON GET_LICHKHAM_DETAIL_FOR_BENHNHAN TO BENHNHAN  
GRANT EXEC ON GET_LICHKHAM_DETAIL_OF_NHASI TO BENHNHAN  
GRANT EXEC ON GET_LICHLAMVIEC_DETAIL_OF_NHASI TO BENHNHAN  
GRANT EXEC ON GET_LICHLAMVIEC_DETAIL_FREE TO BENHNHAN  
GRANT EXEC ON GET_LICHLAMVIEC_DETAIL_FREE_OF_NHASI TO BENHNHAN  
GRANT EXEC ON GET_CHITIETPHIENKHAM_DETAIL TO BENHNHAN  
GRANT EXEC ON GET_DICHVUCHIDINH_DETAIL TO BENHNHAN  
GRANT EXEC ON GET_TOATHUOC_DETAIL TO BENHNHAN  
GRANT EXEC ON INSERT_INTO_BENHNHAN TO BENHNHAN  
GRANT EXEC ON REGISTER_LICHKHAM TO BENHNHAN  
GRANT EXEC ON DROP_LICHKHAM TO BENHNHAN  
GRANT EXEC ON UPDATE_INFO_BENHNHAN TO BENHNHAN  
GRANT EXEC ON CHANGE_LICHKHAM TO BENHNHAN  
GRANT EXEC ON SIGIN TO BENHNHAN


GRANT EXEC ON GET_INFO_NHANVIEN TO NHASI 
GRANT EXEC ON GET_INFO_NHANVIEN_BY_ID TO NHASI  
GRANT EXEC ON GET_INFO_NHANVIEN_BY_NAME TO NHASI 
GRANT EXEC ON GET_INFO_NHANVIEN_BY_PHONENUMBER TO NHASI
GRANT EXEC ON GET_INFO_NHASI TO NHASI 
GRANT EXEC ON GET_INFO_NHASI_BY_ID TO NHASI
GRANT EXEC ON GET_INFO_BENHNHAN_BY_ID TO NHASI  
GRANT EXEC ON GET_INFO_BENHNHAN_BY_NAME TO NHASI  
GRANT EXEC ON GET_INFO_BENHNHAN_BY_PHONENUMBER TO NHASI  
GRANT EXEC ON GET_INFO_THUOC TO NHASI  
GRANT EXEC ON GET_INFO_THUOC_BY_ID TO NHASI  
GRANT EXEC ON GET_INFO_THUOC_BY_NAME TO NHASI  
GRANT EXEC ON GET_INFO_DICHVU TO NHASI  
GRANT EXEC ON GET_INFO_DICHVU_BY_NAME TO NHASI  
GRANT EXEC ON GET_LICHKHAM_DETAIL TO NHASI  
GRANT EXEC ON GET_LICHKHAM_DETAIL_OF_NHASI TO NHASI  
GRANT EXEC ON GET_LICHKHAM_DETAIL_DONE TO NHASI  
GRANT EXEC ON GET_LICHKHAM_DETAIL_DONE_OF_NHASI TO NHASI  
GRANT EXEC ON GET_LICHKHAM_DETAIL_UNFINISHED TO NHASI  
GRANT EXEC ON GET_LICHKHAM_DETAIL_UNFINISHED_OF_NHASI TO NHASI  
GRANT EXEC ON GET_LICHLAMVIEC_DETAIL TO NHASI  
GRANT EXEC ON GET_LICHKHAM_DETAIL_OF_NHASI TO NHASI  
GRANT EXEC ON GET_LICHLAMVIEC_DETAIL_OF_NHASI TO NHASI  
GRANT EXEC ON GET_LICHLAMVIEC_DETAIL_FREE TO NHASI  
GRANT EXEC ON GET_LICHLAMVIEC_DETAIL_FREE_OF_NHASI TO NHASI  
GRANT EXEC ON GET_LICHLAMVIEC_DETAIL_REGISTRED TO NHASI  
GRANT EXEC ON GET_LICHLAMVIEC_DETAIL_REGISTRED_OF_NHASI TO NHASI  
GRANT EXEC ON GET_CHITIETPHIENKHAM_DETAIL TO NHASI  
GRANT EXEC ON GET_DICHVUCHIDINH_DETAIL TO NHASI  
GRANT EXEC ON GET_TOATHUOC_DETAIL TO NHASI  
GRANT EXEC ON INSERT_INTO_LICHLAMVIEC TO NHASI  
GRANT EXEC ON INSERT_INTO_CHITIETPHIENKHAM TO NHASI  
GRANT EXEC ON INSERT_INTO_TOATHUOC TO NHASI  
GRANT EXEC ON INSERT_INTO_DICHVUCHIDINH TO NHASI  
GRANT EXEC ON REGISTER_LICHKHAM TO NHASI
GRANT EXEC ON INSERT_INTO_BENHNHAN TO NHASI    
GRANT EXEC ON CHANGE_LICHLAMVIEC TO NHASI  

GRANT EXEC ON GET_INFO_NHANVIEN TO NHANVIEN 
GRANT EXEC ON GET_INFO_NHANVIEN_BY_ID TO NHANVIEN  
GRANT EXEC ON GET_INFO_NHASI TO NHANVIEN 
GRANT EXEC ON GET_INFO_NHASI_BY_ID TO NHANVIEN
GRANT EXEC ON GET_INFO_NHASI_BY_NAME TO NHANVIEN 
GRANT EXEC ON GET_INFO_NHASI_BY_PHONENUMBER TO NHANVIEN
GRANT EXEC ON GET_INFO_BENHNHAN_BY_ID TO NHANVIEN  
GRANT EXEC ON GET_INFO_BENHNHAN_BY_NAME TO NHANVIEN  
GRANT EXEC ON GET_INFO_BENHNHAN_BY_PHONENUMBER TO NHANVIEN  
GRANT EXEC ON GET_INFO_THUOC TO NHANVIEN  
GRANT EXEC ON GET_INFO_THUOC_BY_ID TO NHANVIEN  
GRANT EXEC ON GET_INFO_THUOC_BY_NAME TO NHANVIEN  
GRANT EXEC ON GET_INFO_DICHVU TO NHANVIEN  
GRANT EXEC ON GET_INFO_DICHVU_BY_NAME TO NHANVIEN  
GRANT EXEC ON GET_LICHKHAM_DETAIL TO NHANVIEN  
GRANT EXEC ON GET_LICHKHAM_DETAIL_OF_NHASI TO NHANVIEN  
GRANT EXEC ON GET_LICHKHAM_DETAIL_DONE TO NHANVIEN  
GRANT EXEC ON GET_LICHKHAM_DETAIL_DONE_OF_NHASI TO NHANVIEN  
GRANT EXEC ON GET_LICHKHAM_DETAIL_UNFINISHED TO NHANVIEN  
GRANT EXEC ON GET_LICHKHAM_DETAIL_UNFINISHED_OF_NHASI TO NHANVIEN  
GRANT EXEC ON GET_LICHLAMVIEC_DETAIL TO NHANVIEN  
GRANT EXEC ON GET_LICHKHAM_DETAIL_OF_NHASI TO NHANVIEN  
GRANT EXEC ON GET_LICHLAMVIEC_DETAIL_OF_NHASI TO NHANVIEN  
GRANT EXEC ON GET_LICHLAMVIEC_DETAIL_FREE TO NHANVIEN  
GRANT EXEC ON GET_LICHLAMVIEC_DETAIL_FREE_OF_NHASI TO NHANVIEN  
GRANT EXEC ON GET_LICHLAMVIEC_DETAIL_REGISTRED TO NHANVIEN  
GRANT EXEC ON GET_LICHLAMVIEC_DETAIL_REGISTRED_OF_NHASI TO NHANVIEN  
GRANT EXEC ON GET_CHITIETPHIENKHAM_DETAIL TO NHANVIEN  
GRANT EXEC ON GET_DICHVUCHIDINH_DETAIL TO NHANVIEN  
GRANT EXEC ON GET_TOATHUOC_DETAIL TO NHANVIEN  
GRANT EXEC ON REGISTER_LICHKHAM TO NHANVIEN  
GRANT EXEC ON INSERT_INTO_LICHLAMVIEC TO NHANVIEN  
GRANT EXEC ON INSERT_INTO_BENHNHAN TO NHANVIEN  
GRANT EXEC ON CHANGE_LICHKHAM TO NHANVIEN  

GRANT EXEC ON GET_INFO_NHANVIEN TO QUANTRI 
GRANT EXEC ON GET_INFO_NHANVIEN_BY_NAME TO QUANTRI 
GRANT EXEC ON GET_INFO_NHANVIEN_BY_ID TO QUANTRI  
GRANT EXEC ON GET_INFO_NHASI TO QUANTRI 
GRANT EXEC ON GET_INFO_NHASI_BY_ID TO QUANTRI
GRANT EXEC ON GET_INFO_NHASI_BY_NAME TO QUANTRI 
GRANT EXEC ON GET_INFO_NHASI_BY_PHONENUMBER TO QUANTRI
GRANT EXEC ON GET_INFO_BENHNHAN TO QUANTRI  
GRANT EXEC ON GET_INFO_BENHNHAN_BY_ID TO QUANTRI  
GRANT EXEC ON GET_INFO_BENHNHAN_BY_NAME TO QUANTRI  
GRANT EXEC ON GET_INFO_BENHNHAN_BY_PHONENUMBER TO QUANTRI  
GRANT EXEC ON GET_INFO_THUOC TO QUANTRI  
GRANT EXEC ON GET_INFO_THUOC_BY_ID TO QUANTRI  
GRANT EXEC ON GET_INFO_THUOC_BY_NAME TO QUANTRI  
GRANT EXEC ON GET_INFO_DICHVU TO QUANTRI  
GRANT EXEC ON GET_INFO_DICHVU_BY_NAME TO QUANTRI  
GRANT EXEC ON GET_CHITIETPHIENKHAM_DETAIL TO QUANTRI  
GRANT EXEC ON GET_DICHVUCHIDINH_DETAIL TO QUANTRI  
GRANT EXEC ON GET_TOATHUOC_DETAIL TO QUANTRI  
GRANT EXEC ON INSERT_INTO_NHASI TO QUANTRI  
GRANT EXEC ON INSERT_INTO_BENHNHAN TO QUANTRI  
GRANT EXEC ON INSERT_INTO_NHANVIEN TO QUANTRI  
GRANT EXEC ON INSERT_INTO_QUANTRI TO QUANTRI  
GRANT EXEC ON INSERT_INTO_DICHVU TO QUANTRI  
GRANT EXEC ON INSERT_INTO_THUOC TO QUANTRI  
GRANT EXEC ON INSERT_INTO_DICHVU TO QUANTRI  
GRANT EXEC ON DROP_THUOC TO QUANTRI  
GRANT EXEC ON DROP_THUOC_EXPIRED TO QUANTRI  
GRANT EXEC ON DROP_DICHVU TO QUANTRI  
GRANT EXEC ON UPDATE_INFO_THUOC TO QUANTRI  
GRANT EXEC ON BLOCK_ACCOUNT_BENHNHAN TO QUANTRI  
GRANT EXEC ON BLOCK_ACCOUNT_NHASI TO QUANTRI  
GRANT EXEC ON BLOCK_ACCOUNT_NHANVIEN TO QUANTRI  
