CREATE DATABASE QLPHONGKHAM
GO
USE QLPHONGKHAM
GO
CREATE OR ALTER PROC CREATE_TABLE
AS
BEGIN TRAN
    BEGIN TRY
        CREATE TABLE BENHNHAN
        (
            MABN CHAR(16) DEFAULT SUBSTRING(CONVERT(CHAR(36), NEWID()), 1, 16),
            DIENTHOAI CHAR(10),
            MATKHAU VARCHAR(32),
            HOTEN NVARCHAR(64),
            NGAYSINH DATE,
            DIACHI NVARCHAR(128),
            DAKHOA BIT
        )

        CREATE TABLE NHANVIEN
        (
            MANV CHAR(16) DEFAULT SUBSTRING(CONVERT(CHAR(36), NEWID()), 1, 16),
            DIENTHOAI CHAR(10),
            MATKHAU VARCHAR(32),
            HOTEN NVARCHAR(64),
            NGAYSINH DATE,
            DAKHOA BIT
        )

        CREATE TABLE QUANTRI
        (
            MAQT CHAR(16) DEFAULT SUBSTRING(CONVERT(CHAR(36), NEWID()), 1, 16),
            DIENTHOAI CHAR(10),
            MATKHAU VARCHAR(32),
            NGAYSINH DATE,
            HOTEN NVARCHAR(64),
        )

        CREATE TABLE NHASI
        (
            MANS CHAR(16) DEFAULT SUBSTRING(CONVERT(CHAR(36), NEWID()), 1, 16),
            DIENTHOAI CHAR(10),
            MATKHAU VARCHAR(32),
            HOTEN NVARCHAR(64),
            NGAYSINH DATE,
            DAKHOA BIT
        )

        CREATE TABLE LICHKHAM
        (
            MABN CHAR(16),
            MANS CHAR(16),
            NGAYKHAM DATE,
            GIOKHAM TIME
        )

        CREATE TABLE LICHLAMVIEC
        (
            MANS CHAR(16),
            NGAYKHAM DATE,
            GIOKHAM TIME
        )

        CREATE TABLE CHITIETPHIENKHAM
        (
            MACT CHAR(13) DEFAULT SUBSTRING(CONVERT(CHAR(36), NEWID()), 1, 13),
            MABN CHAR(16),
            MANS CHAR(16),
            NGAYKHAM DATE,
            GIOKHAM TIME,
            TONGTIEN BIGINT DEFAULT 0,
            CHANDOAN NVARCHAR(512),
            TRIEUCHUNG NVARCHAR(512),
        )

        CREATE TABLE TOATHUOC
        (
            MACT CHAR(13),
            MALO CHAR(12),
            MATHUOC CHAR(10),
            SOLUONG INT,
            LIEULUONG NVARCHAR(32),
            THANHTIEN INT
        )

        CREATE TABLE DICHVUCHIDINH
        (
            MACT CHAR(13),
            MADV CHAR(9),
            THANHTIEN INT
        )

        CREATE TABLE DICHVU
        (
            MADV CHAR(9) DEFAULT SUBSTRING(CONVERT(CHAR(36), NEWID()), 1, 9),
            TENDV NVARCHAR(64),
            DONGIA INT
        )

        CREATE TABLE THUOC
        (
            MALO CHAR(12) DEFAULT SUBSTRING(CONVERT(CHAR(36), NEWID()), 1, 12),
            MATHUOC CHAR(10) DEFAULT SUBSTRING(CONVERT(CHAR(36), NEWID()), 1, 10),
            TENTHUOC NVARCHAR(32),
            DONVI VARCHAR(10),
            CHIDINH NVARCHAR(128),
            SOLUONG INT,
            NGAYHETHAN DATE,
            DONGIA INT
        )
    

        /*NOT NULL */
        --R21
        ALTER TABLE BENHNHAN ALTER COLUMN MABN CHAR(16) NOT NULL;
        ALTER TABLE BENHNHAN ALTER COLUMN DIENTHOAI CHAR(10) NOT NULL;
        ALTER TABLE BENHNHAN ALTER COLUMN HOTEN NVARCHAR(64) NOT NULL;

        --R22
        ALTER TABLE NHANVIEN ALTER COLUMN MANV CHAR(16) NOT NULL;
        ALTER TABLE NHANVIEN ALTER COLUMN DIENTHOAI CHAR(10) NOT NULL;
        ALTER TABLE NHANVIEN ALTER COLUMN HOTEN NVARCHAR(64) NOT NULL;

        --R23
        ALTER TABLE NHASI ALTER COLUMN MANS CHAR(16) NOT NULL;
        ALTER TABLE NHASI ALTER COLUMN DIENTHOAI CHAR(16) NOT NULL;
        ALTER TABLE NHASI ALTER COLUMN HOTEN NVARCHAR(64) NOT NULL;

        --R24
        ALTER TABLE QUANTRI ALTER COLUMN MAQT CHAR(16) NOT NULL;
        ALTER TABLE QUANTRI ALTER COLUMN DIENTHOAI CHAR(10) NOT NULL;
        ALTER TABLE QUANTRI ALTER COLUMN HOTEN NVARCHAR(64) NOT NULL;

        --R25
        ALTER TABLE LICHKHAM ALTER COLUMN MANS CHAR(16) NOT NULL;
        ALTER TABLE LICHKHAM ALTER COLUMN MABN CHAR(16) NOT NULL;
        ALTER TABLE LICHKHAM ALTER COLUMN NGAYKHAM DATE NOT NULL;
        ALTER TABLE LICHKHAM ALTER COLUMN GIOKHAM TIME NOT NULL;

        --R26
        ALTER TABLE LICHLAMVIEC ALTER COLUMN MANS CHAR(16) NOT NULL;
        ALTER TABLE LICHLAMVIEC ALTER COLUMN NGAYKHAM DATE NOT NULL;
        ALTER TABLE LICHLAMVIEC ALTER COLUMN GIOKHAM TIME NOT NULL;

        --R27
        ALTER TABLE TOATHUOC ALTER COLUMN SOLUONG INT NOT NULL;
        ALTER TABLE TOATHUOC ALTER COLUMN LIEULUONG NVARCHAR(32) NOT NULL;
        ALTER TABLE TOATHUOC ALTER COLUMN MACT CHAR(13) NOT NULL;
        ALTER TABLE TOATHUOC ALTER COLUMN MALO CHAR(12) NOT NULL;
        ALTER TABLE TOATHUOC ALTER COLUMN MATHUOC CHAR(10) NOT NULL;

        --R28
        ALTER TABLE CHITIETPHIENKHAM ALTER COLUMN MACT CHAR(13) NOT NULL;

        --R29
        ALTER TABLE DICHVUCHIDINH ALTER COLUMN MACT CHAR(13) NOT NULL;
        ALTER TABLE DICHVUCHIDINH ALTER COLUMN MADV CHAR(9) NOT NULL;

        --R30
        ALTER TABLE DICHVU ALTER COLUMN MADV CHAR(9) NOT NULL;

        --R31
        ALTER TABLE THUOC ALTER COLUMN TENTHUOC NVARCHAR(32) NOT NULL;
        ALTER TABLE THUOC ALTER COLUMN MALO CHAR(12) NOT NULL;
        ALTER TABLE THUOC ALTER COLUMN SOLUONG CHAR(8) NOT NULL;
        ALTER TABLE THUOC ALTER COLUMN DONGIA CHAR(8) NOT NULL;
        ALTER TABLE THUOC ALTER COLUMN NGAYHETHAN DATE NOT NULL;
        ALTER TABLE THUOC ALTER COLUMN MATHUOC CHAR(10) NOT NULL;

        /*UNIQUE*/
        --R1
        ALTER TABLE QUANTRI ADD UNIQUE (DIENTHOAI);

        --R2
        ALTER TABLE BENHNHAN ADD UNIQUE (DIENTHOAI);

        --R3
        ALTER TABLE NHANVIEN ADD UNIQUE (DIENTHOAI);

        --R4
        ALTER TABLE NHASI ADD UNIQUE (DIENTHOAI);

        ALTER TABLE THUOC ADD UNIQUE (TENTHUOC);

        ALTER TABLE DICHVU ADD UNIQUE (TENDV);

        /*Add primary key*/
        --R5
        ALTER TABLE BENHNHAN ADD PRIMARY KEY (MABN);

        --R6
        ALTER TABLE NHANVIEN ADD PRIMARY KEY (MANV);

        --R7
        ALTER TABLE QUANTRI ADD PRIMARY KEY (MAQT);

        --R8
        ALTER TABLE NHASI ADD PRIMARY KEY (MANS);

        --R9
        ALTER TABLE LICHKHAM ADD PRIMARY KEY (MANS, NGAYKHAM, GIOKHAM);

        --R10
        ALTER TABLE LICHLAMVIEC ADD PRIMARY KEY (MANS, NGAYKHAM, GIOKHAM);

        --R11
        ALTER TABLE CHITIETPHIENKHAM ADD PRIMARY KEY (MACT);

        --R12
        ALTER TABLE TOATHUOC ADD PRIMARY KEY (MACT, MALO, MATHUOC);

        --13
        ALTER TABLE DICHVUCHIDINH ADD PRIMARY KEY (MACT, MADV);

        --R14
        ALTER TABLE DICHVU ADD PRIMARY KEY (MADV);

        --R15
        ALTER TABLE THUOC ADD PRIMARY KEY (MALO, MATHUOC);

        -- ADD FOREIGN KEY
        --R16
        ALTER TABLE LICHKHAM ADD CONSTRAINT FK_LICHKHAM_BENHNHAN FOREIGN KEY (MABN) REFERENCES BENHNHAN(MABN);

        --R51
        ALTER TABLE LICHKHAM ADD CONSTRAINT FK_LICHKHAM_LICHLAMVIEC FOREIGN KEY (MANS, NGAYKHAM, GIOKHAM) REFERENCES LICHLAMVIEC(MANS, NGAYKHAM, GIOKHAM);

        --R17
        ALTER TABLE TOATHUOC ADD CONSTRAINT FK_TOATHUOC_CHITIETPHIENKHAM FOREIGN KEY (MACT) REFERENCES CHITIETPHIENKHAM(MACT);
        ALTER TABLE TOATHUOC ADD CONSTRAINT FK_TOATHUOC_THUOC FOREIGN KEY (MALO, MATHUOC) REFERENCES THUOC(MALO, MATHUOC);

        --R18
        ALTER TABLE DICHVUCHIDINH ADD CONSTRAINT FK_DICHVUCHIDINH_CHITIETPHIENKHAM FOREIGN KEY (MACT) REFERENCES CHITIETPHIENKHAM(MACT);
        ALTER TABLE DICHVUCHIDINH ADD CONSTRAINT FK_DICHVUCHIDINH_DICHVU FOREIGN KEY (MADV) REFERENCES DICHVU(MADV);

        --R19
        ALTER TABLE LICHLAMVIEC ADD CONSTRAINT FK_LICHLAMVIEC_NHASI FOREIGN KEY (MANS) REFERENCES NHASI(MANS);

        --R20
        ALTER TABLE CHITIETPHIENKHAM ADD CONSTRAINT FK_CHITIETPHIENKHAM_LICHKHAM FOREIGN KEY (MANS, NGAYKHAM, GIOKHAM) REFERENCES LICHKHAM(MANS, NGAYKHAM, GIOKHAM);

        --R32
        ALTER TABLE BENHNHAN ADD CHECK (DATEDIFF(yy, NGAYSINH,  GETDATE()) >= 6)

        --R33
        ALTER TABLE THUOC ADD CHECK (SOLUONG >= 0)
END TRY
    BEGIN CATCH
        ROLLBACK TRAN
        THROW
    END CATCH
COMMIT

GO
EXEC CREATE_TABLE